Caodj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^backend/', include('backend.urls')),
    url(r'^', include('web.urls')),

    # path('blog/login.html/',views.login),
    # path('blog/register.html/',views.register),
    # path('blog/home/',views.blog.home),
    # path('blog/new/',views.blog.new),
    # path('blog/good/',views.blog.good),
]

web/urls.py
from django.conf.urls import url
from django.urls import path
from .views import home
from .views import account

urlpatterns = [
    url(r'^login.html$', account.login),
    # url(r'^xiaoyun.html$', account.xiaoyun),
    # url(r'^shizhengwen.html$', account.shizhengwen),
    url(r'^logout.html$', account.logout),
    url(r'^register.html$', account.register),
    url(r'^uploadimg.html$',home.upload_img),
    url(r'^check_code.html$', account.check_code),
    url(r'^all/(?P<article_type_id>\d+).html$', home.index, name='index'),
    url(r'^(?P<site>\w+).html$', home.home),
    url(r'^(?P<site>\w+)/(?P<condition>((tag)|(date)|(category)))/(?P<val>\w+-*\w*).html$', home.filter),
    url(r'^(?P<site>\w+)/(?P<nid>\d+).html$', home.detail),
    url(r'^', home.index),

]

repository/models.py
from django.db import models
class UserInfo(models.Model):
    """
    用户表
    """
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name='用户名', max_length=32, unique=True)
    password = models.CharField(verbose_name='密码', max_length=64)
    nickname = models.CharField(verbose_name='昵称', max_length=32,null=True)
    email = models.EmailField(verbose_name='邮箱', unique=True)
    avatar = models.ImageField(verbose_name='头像',null=True)

    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    fans = models.ManyToManyField(verbose_name='粉丝们',
                                  to='UserInfo',
                                  through='UserFans',
                                  related_name='f',
                                  through_fields=('user', 'follower'))
class Blog(models.Model):
    """
    博客信息
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客前缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)
    user = models.OneToOneField(to='UserInfo', to_field='nid',on_delete=None)
class UserFans(models.Model):
    """
    互粉关系表
    """
    user = models.ForeignKey(verbose_name='博主', to='UserInfo', to_field='nid', related_name='users',on_delete=None)
    follower = models.ForeignKey(verbose_name='粉丝', to='UserInfo', to_field='nid', related_name='followers',on_delete=None)

    class Meta:
        unique_together = [
            ('user', 'follower'),
        ]
class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)

    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid',on_delete=None)
class ArticleDetail(models.Model):
    """
    文章详细表
    """
    content = models.TextField(verbose_name='文章内容', )

    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid',on_delete=None)
class UpDown(models.Model):
    """
    文章顶或踩
    """
    article = models.ForeignKey(verbose_name='文章', to='Article', to_field='nid',on_delete=None)
    user = models.ForeignKey(verbose_name='赞或踩用户', to='UserInfo', to_field='nid',on_delete=None)
    up = models.BooleanField(verbose_name='是否赞')

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]
class Comment(models.Model):
    """
    评论表
    """
    nid = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复评论', to='self', related_name='back', null=True,on_delete=None)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid',on_delete=None)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid',on_delete=None)
class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid',on_delete=None)
class Article(models.Model):
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题', max_length=128)
    summary = models.CharField(verbose_name='文章简介', max_length=255)
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid',on_delete=None)
    category = models.ForeignKey(verbose_name='文章类型', to='Category', to_field='nid', null=True,on_delete=None)

    type_choices = [
        (1, "Python"),
        (2, "Linux"),
        (3, "OpenStack"),
        (4, "GoLang"),
    ]
    # 1,2,3,4
    article_type_id = models.IntegerField(choices=type_choices, default=None)

    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )
class Article2Tag(models.Model):
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid',on_delete=None)
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid',on_delete=None)

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

web/views/home.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.shortcuts import render,HttpResponse
from django.shortcuts import redirect
from repository import models
from utils.pagination import Pagination
from django.urls import reverse
import json
from django.conf import settings
from django.http import JsonResponse
import os
import sys
import datetime as dt
import  uuid
def index(request, *args, **kwargs):
    """
    博客首页，展示全部博文
    :param request:
    :return:
    """
    # return render(request,'index.html')
    # 获取文章类型
    article_type_list = models.Article.type_choices
    # {},[]
    if kwargs:
        article_type_id = int(kwargs['article_type_id'])
        base_url = reverse('index',kwargs=kwargs)#   all/1.html
    else:
        article_type_id = None
        base_url = '/' # /

    data_count = models.Article.objects.filter(**kwargs).count()


    page_obj = Pagination(request.GET.get('p'),data_count)
    article_list = models.Article.objects.filter(**kwargs).order_by('-nid')[page_obj.start:page_obj.end]
    page_str = page_obj.page_str(base_url)

    return render(
        request,
        'index.html',
        {
            'article_list': article_list,
            'article_type_id': article_type_id,
            'article_type_list': article_type_list,
            'page_str': page_str,
        }
    )


def home(request, site):
    """
    博主个人首页
    :param request:
    :param site: 博主的网站后缀如：http://xxx.com/wupeiqi.html
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/')
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%Y-%m",create_time) as ctime from repository_article group by strftime("%Y-%m",create_time)')

    article_list = models.Article.objects.filter(blog=blog).order_by('-nid').all()

    return render(
        request,
        'home.html',
        {
            'blog': blog,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
            'article_list': article_list
        }
    )


def filter(request, site, condition, val):
    """
    分类显示
    :param request:
    :param site:
    :param condition:
    :param val:
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/')
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%Y-%m",create_time) as ctime from repository_article group by strftime("%Y-%m",create_time)')

    template_name = "home_summary_list.html"
    if condition == 'tag':
        template_name = "home_title_list.html"
        article_list = models.Article.objects.filter(tags=val, blog=blog).all()
    elif condition == 'category':
        article_list = models.Article.objects.filter(category_id=val, blog=blog).all()
    elif condition == 'date':
        # article_list = models.Article.objects.filter(blog=blog).extra(
        # where=['date_format(create_time,"%%Y-%%m")=%s'], params=[val, ]).all()
        article_list = models.Article.objects.filter(blog=blog).extra(
            where=['strftime("%%Y-%%m",create_time)=%s'], params=[val, ]).all()
    else:
        article_list = []

    return render(
        request,
        template_name,
        {
            'blog': blog,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
            'article_list': article_list
        }
    )


def detail(request, site, nid):
    """
    博文详细页
    :param request:
    :param site:
    :param nid:
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%Y-%m",create_time) as ctime from repository_article group by strftime("%Y-%m",create_time)')

    article = models.Article.objects.filter(blog=blog, nid=nid).select_related('category', 'articledetail').first()
    comment_list = models.Comment.objects.filter(article=article).select_related('reply')


    return render(
        request,
        'home_detail.html',
        {
            'blog': blog,
            'article': article,
            'comment_list': comment_list,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
        }

    )


def upload_img(request, dir_name):
        ##################
        #  kindeditor图片上传返回数据格式说明：
        # {"error": 1, "message": "出错信息"}
        # {"error": 0, "url": "图片地址"}
        ##################
        result = {"error": 1, "message": "上传出错"}
        files = request.FILES.get("imgFile", None)
        if files:
            result = image_upload(files, dir_name)
        return HttpResponse(json.dumps(result), content_type="application/json")
    # 目录创建
def upload_generation_dir(dir_name):
        today = dt.datetime.today()
        dir_name = dir_name + '/%d/%d/' % (today.year, today.month)
        if not os.path.exists(settings.MEDIA_ROOT + dir_name):
            os.makedirs(settings.MEDIA_ROOT + dir_name)
        return dir_name

    # 图片上传

def image_upload(files, dir_name):

        # 允许上传文件类型

        allow_suffix = ['jpg', 'png', 'jpeg', 'gif', 'bmp']

        file_suffix = files.name.split(".")[-1]

        if file_suffix not in allow_suffix:
            return {"error": 1, "message": "图片格式不正确"}

        relative_path_file = upload_generation_dir(dir_name)

        path = os.path.join(settings.MEDIA_ROOT, relative_path_file)

        if not os.path.exists(path):  # 如果目录不存在创建目录

            os.makedirs(path)

        file_name = str(uuid.uuid1()) + "." + file_suffix

        path_file = os.path.join(path, file_name)

        file_url = settings.MEDIA_URL + relative_path_file + file_name

        open(path_file, 'wb').write(files.file.read())  # 保存图片

        return {"error": 0, "url": file_url}

templates/backend_article.html
{% extends 'backend_layout.html' %}
{% load search %}
{% block css %}
<style>
    .conditions a{
        display: inline-block;
        padding: 2px 5px;
        margin-left: 5px;
    }
    .conditions a.active{
        background-color: #b35215;
        color: #ffffff;
    }
</style>
{% endblock %}
{% block conent %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">文章列表</li>
    </ol>
    <div>

        <div style="border: 1px dashed #dddddd;padding: 8px;border-left: 3px solid #337ab7;">
            <i class="fa fa-search" aria-hidden="true"></i> 搜索条件
        </div>
        <div style="padding: 10px">
            <div class="conditions row clearfix" style="margin: 0;padding: 8px 0;">
                <div class="col-xs-1" style="text-align: right">
                    {% category_all arg_dict %}
                </div>
                <div class="col-xs-11">
                    {% category_combine category_list arg_dict %}
                </div>
            </div>
            <div class="conditions row clearfix" style="margin: 0;padding: 8px 0;">
                <div class="col-xs-1" style="text-align: right">
                    {% article_type_all arg_dict %}
                </div>
                <div class="col-xs-11">
                    {% article_type_combine type_list arg_dict %}
                </div>
            </div>
        </div>
        <div class="clearfix"
             style="height: 36px;line-height: 35px;padding: 0 15px;border-top: 1px solid #dddddd;background-color: #f1f0f0">
            <i class="fa fa-table" aria-hidden="true"></i>
            搜索文章({{ data_count }}篇)
            <a target="_blank" href="/backend/add-article.html" class="right"
               style="display: inline-block;padding:0 10px;background-color: #428bca;color: #ffffff;">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                创建新文章
            </a>
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>文章标题</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in result %}
                <tr nid="{{ row.nid }}">
                    <td><a href="/{{ row.blog.site }}/{{ row.nid }}.html">{{ row.title }}</a></td>
                    <td>
                        <a class="btn btn-danger btn-xs">
                            <i class="fa fa-times" aria-hidden="true"></i>
                            删除
                        </a>
                        |
                        <a class="btn btn-primary btn-xs" href="/backend/edit-article-{{ row.nid }}.html">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            编辑
                        </a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
               {{ page_str }}
            </ul>
        </div>
    </div>


{% endblock %}

{% block js %}

{% endblock %}

templates/backend_base_info.html
{% extends 'backend_layout.html' %}
{% block css %}
    <style>
        .form-horizontal .control-label {
            padding-top: 7px;
            margin-bottom: 0;
            text-align: right;
        }

        .avatar-container {
            height: 200px;
            width: 200px;
            padding: 2px;
            border: 1px solid #dddddd;
            position: relative;
        }

        .avatar-container img {
            height: 100%;
            width: 100%;
            border: 0;
            overflow: hidden;
        }

        .avatar-container .text {
            text-align: center;
        }

        .avatar-container .img-file {
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            opacity: 0;
            position: absolute;
            z-index: 102;
        }
    </style>
{% endblock %}
{% block conent %}
    <ol class="breadcrumb">
        <li><a href="#">用户管理</a></li>
        <li class="active">用户信息</li>
    </ol>
    <div>

        <div class="row" style="position: relative;">
            <form class="form-horizontal" action="/backend/base_info.html" method="post">
                <div class="col-xs-12">
                    <div class="form-group">
                        <label class="col-xs-2 control-label">用户名</label>

                        <div class="col-xs-5">
                            <p class="form-control-static">{{ request.session.user_info.username }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 control-label">邮箱</label>

                        <div class="col-xs-5">
                            <p class="form-control-static">{{ request.session.user_info.email }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="nickname" class="col-xs-2 control-label">昵称</label>

                        <div class="col-xs-5">
                            <input type="text" class="form-control" id="nickname" placeholder="请输入昵称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="blogUrl" class="col-xs-2 control-label">博客地址</label>

                        <div class="col-xs-5">
                            <input type="text" class="form-control" id="blogUrl"
                                   placeholder="如：wupeiqi,则个人博客为http://www.xxx.com/wupeiqi.html">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="blogTheme" class="col-xs-2 control-label">博客主题</label>

                        <div class="col-xs-5">
                            <select id="blogTheme" class="form-control">
                                <option value="">默认主题</option>
                                <option value="">红色火焰</option>
                                <option value="">嘿嘿哈嘿</option>
                                <option value="">哈哈哈嘿哈</option>
                                <option value="">编不出来了</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="blogTitle" class="col-xs-2 control-label">博客标题内容</label>

                        <div class="col-xs-8">
                            <textarea id="blogTitle" style="min-height: 100px" class="form-control"
                                      placeholder="give some text"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-offset-2 col-xs-10">
                            <button type="submit" class="btn btn-primary">保 存</button>
                        </div>
                    </div>

                </div>
            </form>
            <div style="position: absolute;" class="col-xs-offset-7 col-xs-5">
                <div class="avatar-container">
                    <iframe style="display: none;" id="upload_iframe" name="upload_iframe"></iframe>
                    <form method="POST" action="/backend/upload-avatar.html" enctype="multipart/form-data"
                          target="upload_iframe">
                        {% csrf_token %}
                        <img id="previewImg" origin="/static/imgs/avatar/default.png"
                             src="/static/imgs/avatar/default.png"
                             style="border-radius: 50%;">

                        <div class="text">点击图片更换(<a href="#">撤销</a>)</div>
                        <input id="avatarImg" name="avatar_img" type="file" class="img-file"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(function () {
            bindChangeAvatar4();
        });

        function bindChangeAvatar1() {
            $('#avatarImg').change(function () {
                var file_obj = $(this)[0].files[0];
                $('#prevViewImg')[0].src = window.URL.createObjectURL(file_obj)
            })
        }

        function bindChangeAvatar2() {
            $('#avatarImg').change(function () {
                var file_obj = $(this)[0].files[0];
                var reader = new FileReader();
                reader.readAsDataURL(file_obj);
                reader.onload = function (e) {
                    $('#previewImg')[0].src = this.result;
                };
            })
        }

        function bindChangeAvatar3() {
            $('#avatarImg').change(function () {
                var file_obj = $(this)[0].files[0];
                var form = new FormData();
                form.add('img_upload', file_obj);

                $.ajax({
                    url: '',
                    data: form,
                    processData: false,  // tell jQuery not to process the data
                    contentType: false,  // tell jQuery not to set contentType
                    success: function (arg) {

                    }
                })
            })
        }

        function bindChangeAvatar4() {
            $('#avatarImg').change(function () {
                $(this).parent().submit();

                $('#upload_iframe').load(function () {
                    var iframeContents = this.contentWindow.document.body.innerText;
                    iframeContents = JSON.parse(iframeContents);
                    if (iframeContents.status) {
                        $('#previewImg').attr('src', '/' + iframeContents.data);
                    }
                })

            })
        }

    </script>
{% endblock %}

templates/backend_category.html
{% extends 'backend_layout.html' %}
{% block css %}

{% endblock %}
{% block conent %}
    <ol class="breadcrumb">
        <li><a href="#">分类管理</a></li>
        <li class="active">分类列表</li>
    </ol>
    <div>
        <div class="row" style="padding: 20px 5px;">
            <form class="form-horizontal" action="/backend/category.html" method="post">
                <div class="col-xs-12">
                    <div class="form-group">
                        <label class="col-xs-1 control-label">分类名称</label>

                        <div class="col-xs-3">
                            <input type="text" class="form-control" id="nickname" placeholder="请输入分类名称" name="nickname">
                        </div>
                        <div class="col-xs-3">
                            <input type="submit" class="btn btn-primary" value="添 加">
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div style="height: 35px;background-color: #f5f5f5;line-height: 35px;padding: 0 15px;">
            <i class="fa fa-table" aria-hidden="true"></i>
            标签列表
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>分类</th>
                <th>文章个数</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {%for row in row_list %}
                <tr nid="{{ row.nid }}">
                <td>{{row.title}}</td>
                <td>{{ row.article_set.count }}</td>
                <td>
                    <a class="btn btn-danger btn-xs" href="javascript:void()" onclick="delcategory(this)">
                        <i class="fa fa-times" aria-hidden="true"></i>
                        删除
                    </a>
                    |
                    <a class="btn btn-primary btn-xs">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        编辑
                    </a>
                </td>
                </tr>
            {%endfor%}
            </tbody>
        </table>

        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
                {{ page_str }}
            </ul>
        </div>
    </div>


{% endblock %}

{% block js %}
<script>
 function delcategory(ths){
     var nid = $(ths).parent().parent().attr("nid");
     $.ajax({
         url:"/backend/delcategory.html",
         type:"POST",
         data:{"nid":nid},
         success:function(arg){
             if(arg='YES'){
                $(ths).parent().parent().remove()
             }else {
                 alert(arg)
             }

         }

     })
 }
</script>
{% endblock %}

templates/backend_edit_article.html
{% extends 'backend_layout.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/plugins/kindeditor/themes/default/default.css"/>
    <style>
        .kind-content {
            width: 100%;
            min-height: 500px;
        }
    </style>
{% endblock %}

{% block conent %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">修改文章</li>
    </ol>
    <div style="padding: 5px 8px;">
        <form method="POST" action="/backend/edit-article-{{ nid }}.html">
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="summary">简介 <span>{{ form.summary.errors.0 }}</span></label>
                {{ form.summary }}
            </div>
            <div class="form-group">
                <label for="content">内容 <span>{{ form.content.errors.0 }}</span></label>
                {{ form.content }}
            </div>
            <div class="form-group">
                <label>类型 <span>{{ form.article_type.errors.0 }}</span></label>

                <div>
                    {{ form.article_type_id }}
                </div>

            </div>
            <div class="form-group">
                <label>分类 <span>{{ form.category_id.errors.0 }}</span></label>

                <div>
                    {{ form.category_id }}
                </div>
            </div>
            <div class="form-group">
                <label>标签 <span>{{ form.tags.errors.0 }}</span></label>

                <div>
                    {{ form.tags }}
                </div>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="保 存">
            </div>
        </form>
    </div>


{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kindeditor/lang/zh_CN.js"></script>
    <script>
        KindEditor.ready(function (K) {
            var editor = K.create('textarea[name="content"]', {
                resizeType: 1
            });
        });
    </script>
{% endblock %}

templates/backend_index.html
{% extends 'backend_layout.html' %}
{% block css %}

{% endblock %}
{% block conent %}
   <h1>欢迎登陆：{{ request.session.user_info.nickname }}</h1>
{% endblock %}

{% block js %}

{% endblock %}

templates/home.html
{% extends 'home_layout.html' %}

{% block content %}

    <div class="summary-list">
        {% for row in article_list %}
            <div class="summary-item">
                <div class="summary-title">
                    <a href="/{{ blog.site }}/{{ row.nid }}.html">{{ row.title }}</a>
                </div>
                <div class="summary-content">
                    {{ row.summary }}
                </div>
                <div class="summary-footer">
                    <span>{{ row.create_time|date:"Y-m-d H:i:s" }}</span>
                    <span>{{ row.user.nickname }}</span>
                    <span>阅读({{ row.read_count }})</span>
                    <a>评论({{ row.comment_count }})</a>
                    <a href="/backend/edit-article-{{ row.nid }}.html">编辑</a>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

templates/home_layout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" href="/static/css/edmure.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
    <link rel="stylesheet" href="/static/css/row-avatar.css"/>
    <link rel="stylesheet" href="/static/css/theme/{{ blog.theme }}.css"/>
    {% block css %}{% endblock %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap/js/bootstrap.js"></script>
</head>
<body>
<div class="pg-header">
    <div class="title">{{ blog.title }}</div>
    <div class="menu-list">
        <a class="menu-item" href="/">首页</a>
        <a class="menu-item" href="/{{ blog.site }}.html">个人首页</a>
        <a class="menu-item" href="/backend/index.html">管理</a>
    </div>
</div>
<div class="pg-body">
    <div class="body-menu">
        <div class="notice">
            <div class="notice-header">公告</div>
            <div class="notice-body">
                <ul>
                    <li>昵称：{{ blog.user.nickname }}</li>
                    <li>粉丝：{{ blog.user.fans.count }}</li>
                    <li>关注：{{ blog.user.f.count }}</li>
                    <li>邮箱：{{ blog.user.email }}</li>
                </ul>
                <div class="memo">
                    真实是人生的命脉，是一切价值的根基。
                </div>
            </div>
        </div>
        <div class="tags">
            <div class="tags-header">标签</div>
            <div class="tags-body">
                <ul>
                    {% for tag in tag_list %}
                        <li><a href="/{{ blog.site }}/tag/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="types">
            <div class="types-header">分类</div>
            <div class="types-body">
                <ul>
                    {% for tag in category_list %}
                        <li><a href="/{{ blog.site }}/category/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a></li>
                    {% endfor %}
                </ul>

            </div>
        </div>
        <div class="dates">
            <div class="dates-header">时间</div>
            <div class="dates-body">
                <ul>
                    {% for tag in date_list %}
                        <li><a href="/{{ blog.site }}/date/{{ tag.ctime }}.html">{{ tag.ctime}}({{ tag.num}})</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="body-content">
        {% block content %}{% endblock %}
    </div>
</div>
    {% block js %}{% endblock %}
</body>
</html>